//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawContract.Providers.ShawNow.ExecuteOrdersWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleOrderHeader", Namespace="http://schemas.datacontract.org/2004/07/Shaw.OrdersServiceBUS")]
    [System.SerializableAttribute()]
    public partial class SampleOrderHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcctNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoldContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HoldOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoldReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderLines LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShawContract.Providers.ShawNow.ExecuteOrdersWS.OrderAddress ShipToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SidemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerritoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TmEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AcctNumber {
            get {
                return this.AcctNumberField;
            }
            set {
                if ((this.AcctNumberField.Equals(value) != true)) {
                    this.AcctNumberField = value;
                    this.RaisePropertyChanged("AcctNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierName {
            get {
                return this.CarrierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierNameField, value) != true)) {
                    this.CarrierNameField = value;
                    this.RaisePropertyChanged("CarrierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoldContact {
            get {
                return this.HoldContactField;
            }
            set {
                if ((object.ReferenceEquals(this.HoldContactField, value) != true)) {
                    this.HoldContactField = value;
                    this.RaisePropertyChanged("HoldContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HoldOrder {
            get {
                return this.HoldOrderField;
            }
            set {
                if ((this.HoldOrderField.Equals(value) != true)) {
                    this.HoldOrderField = value;
                    this.RaisePropertyChanged("HoldOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoldReason {
            get {
                return this.HoldReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.HoldReasonField, value) != true)) {
                    this.HoldReasonField = value;
                    this.RaisePropertyChanged("HoldReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderLines Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNumber {
            get {
                return this.PoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNumberField, value) != true)) {
                    this.PoNumberField = value;
                    this.RaisePropertyChanged("PoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterField, value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShawContract.Providers.ShawNow.ExecuteOrdersWS.OrderAddress ShipToAddress {
            get {
                return this.ShipToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressField, value) != true)) {
                    this.ShipToAddressField = value;
                    this.RaisePropertyChanged("ShipToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sidemark {
            get {
                return this.SidemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.SidemarkField, value) != true)) {
                    this.SidemarkField = value;
                    this.RaisePropertyChanged("Sidemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Territory {
            get {
                return this.TerritoryField;
            }
            set {
                if ((object.ReferenceEquals(this.TerritoryField, value) != true)) {
                    this.TerritoryField = value;
                    this.RaisePropertyChanged("Territory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TmEmail {
            get {
                return this.TmEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.TmEmailField, value) != true)) {
                    this.TmEmailField = value;
                    this.RaisePropertyChanged("TmEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAddress", Namespace="http://schemas.datacontract.org/2004/07/Shaw.OrdersService.DTO")]
    [System.SerializableAttribute()]
    public partial class OrderAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name2 {
            get {
                return this.Name2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name2Field, value) != true)) {
                    this.Name2Field = value;
                    this.RaisePropertyChanged("Name2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SampleOrderLines", Namespace="http://schemas.datacontract.org/2004/07/Shaw.OrdersServiceBUS", ItemName="SampleOrderLine")]
    [System.SerializableAttribute()]
    public class SampleOrderLines : System.Collections.Generic.List<ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderLine> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleOrderLine", Namespace="http://schemas.datacontract.org/2004/07/Shaw.OrdersServiceBUS")]
    [System.SerializableAttribute()]
    public partial class SampleOrderLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineNbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwatchFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName {
            get {
                return this.ColorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorNameField, value) != true)) {
                    this.ColorNameField = value;
                    this.RaisePropertyChanged("ColorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineNbr {
            get {
                return this.LineNbrField;
            }
            set {
                if ((object.ReferenceEquals(this.LineNbrField, value) != true)) {
                    this.LineNbrField = value;
                    this.RaisePropertyChanged("LineNbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateCode {
            get {
                return this.PrivateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateCodeField, value) != true)) {
                    this.PrivateCodeField = value;
                    this.RaisePropertyChanged("PrivateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateStyle {
            get {
                return this.PrivateStyleField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateStyleField, value) != true)) {
                    this.PrivateStyleField = value;
                    this.RaisePropertyChanged("PrivateStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SideMark {
            get {
                return this.SideMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.SideMarkField, value) != true)) {
                    this.SideMarkField = value;
                    this.RaisePropertyChanged("SideMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleName {
            get {
                return this.StyleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleNameField, value) != true)) {
                    this.StyleNameField = value;
                    this.RaisePropertyChanged("StyleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SwatchFlag {
            get {
                return this.SwatchFlagField;
            }
            set {
                if ((this.SwatchFlagField.Equals(value) != true)) {
                    this.SwatchFlagField = value;
                    this.RaisePropertyChanged("SwatchFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeSet {
            get {
                return this.TypeSetField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeSetField, value) != true)) {
                    this.TypeSetField = value;
                    this.RaisePropertyChanged("TypeSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservices.shawonline.com/SampleOrderService/v1_0", ConfigurationName="ExecuteOrdersWS.IOrderSample")]
    public interface IOrderSample {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.shawonline.com/SampleOrderService/v1_0/IOrderSample/CreateSam" +
            "pleOrder", ReplyAction="https://webservices.shawonline.com/SampleOrderService/v1_0/IOrderSample/CreateSam" +
            "pleOrderResponse")]
        ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader CreateSampleOrder(ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader sampleOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservices.shawonline.com/SampleOrderService/v1_0/IOrderSample/CreateSam" +
            "pleOrder", ReplyAction="https://webservices.shawonline.com/SampleOrderService/v1_0/IOrderSample/CreateSam" +
            "pleOrderResponse")]
        System.Threading.Tasks.Task<ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader> CreateSampleOrderAsync(ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader sampleOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderSampleChannel : ShawContract.Providers.ShawNow.ExecuteOrdersWS.IOrderSample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderSampleClient : System.ServiceModel.ClientBase<ShawContract.Providers.ShawNow.ExecuteOrdersWS.IOrderSample>, ShawContract.Providers.ShawNow.ExecuteOrdersWS.IOrderSample {
        
        public OrderSampleClient() {
        }
        
        public OrderSampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderSampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderSampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderSampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader CreateSampleOrder(ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader sampleOrder) {
            return base.Channel.CreateSampleOrder(sampleOrder);
        }
        
        public System.Threading.Tasks.Task<ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader> CreateSampleOrderAsync(ShawContract.Providers.ShawNow.ExecuteOrdersWS.SampleOrderHeader sampleOrder) {
            return base.Channel.CreateSampleOrderAsync(sampleOrder);
        }
    }
}
