version: 0.2

env:
  variables:
    SOLUTION: ShawContract\ShawContract.sln
    PROJECT: ShawContract\ShawContract.csproj
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore ShawContract.sln -PackagesDirectory packages
      - msbuild shawContract.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="C:\codebuild\artifacts"
artifacts:
  files:
    - '**/*'
  base-directory: C:\codebuild\artifacts