version: 0.2

env:
  variables:
    SOLUTION: ShawContract.sln
    PROJECT: ShawContract\ShawContract.csproj
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore ShawContract\ShawContract.sln -PackagesDirectory packages
      - msbuild ShawContract\ShawContract.sln /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
artifacts:
  files:
    - '**/*'
  base-directory: C:\codebuild\artifacts\_PublishedWebsites\${env:PROJECT}_Package\Archive\