version: 0.2

env:
  variables:
    PROJECT: ShawContract
    DOTNET_FRAMEWORK: 4.7.2
phases:
  build:
    commands:
      - nuget restore ShawContract.sln -PackagesDirectory packages
      - msbuild ShawContract\ShawContract.csproj /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package -v:d
  post_build:
    commands: 
      - move .ebextensions C:\codebuild\artifacts\_PublishedWebsites\ShawContract_Package\Archive\
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\ShawContract_Package\Archive\'