version: 0.2

env:
  variables:
    PROJECT: ShawContract
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore ShawContract.sln -PackagesDirectory packages
      - msbuild ShawContract\ShawContract.csproj /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
  post_build:
    commands:
       create_post_dir:
       command: md C:\Program Files\Amazon\ElasticBeanstalk\hooks\appdeploy\post
       files: C:\Program Files\Amazon\ElasticBeanstalk\hooks\appdeploy\post\800envvar.ps1  
          content:| Get-ChildItem -Path Env:\ | Out-File -FilePath c:\temp\envvar.txt
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\ShawContract_Package\Archive\'
