//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GenericContent.CLASS_NAME, typeof(GenericContent))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type GenericContent.
	/// </summary>
	public partial class GenericContent : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.GenericContent";


		/// <summary>
		/// The instance of the class that provides extended API for working with GenericContent fields.
		/// </summary>
		private readonly GenericContentFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GenericContentID.
		/// </summary>
		[DatabaseIDField]
		public int GenericContentID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GenericContentID"), 0);
			}
			set
			{
				SetValue("GenericContentID", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with GenericContent fields.
		/// </summary>
		[RegisterProperty]
		public GenericContentFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GenericContent fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GenericContentFields : AbstractHierarchicalObject<GenericContentFields>
		{
			/// <summary>
			/// The content item of type GenericContent that is a target of the extended API.
			/// </summary>
			private readonly GenericContent mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GenericContentFields" /> class with the specified content item of type GenericContent.
			/// </summary>
			/// <param name="instance">The content item of type GenericContent that is a target of the extended API.</param>
			public GenericContentFields(GenericContent instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GenericContentID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.GenericContentID;
				}
				set
				{
					mInstance.GenericContentID = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GenericContent" /> class.
		/// </summary>
		public GenericContent() : base(CLASS_NAME)
		{
			mFields = new GenericContentFields(this);
		}

		#endregion
	}
}