//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(LandingPage.CLASS_NAME, typeof(LandingPage))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type LandingPage.
	/// </summary>
	public partial class LandingPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.LandingPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with LandingPage fields.
		/// </summary>
		private readonly LandingPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// LandingPageID.
		/// </summary>
		[DatabaseIDField]
		public int LandingPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("LandingPageID"), 0);
			}
			set
			{
				SetValue("LandingPageID", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with LandingPage fields.
		/// </summary>
		[RegisterProperty]
		public LandingPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with LandingPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class LandingPageFields : AbstractHierarchicalObject<LandingPageFields>
		{
			/// <summary>
			/// The content item of type LandingPage that is a target of the extended API.
			/// </summary>
			private readonly LandingPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="LandingPageFields" /> class with the specified content item of type LandingPage.
			/// </summary>
			/// <param name="instance">The content item of type LandingPage that is a target of the extended API.</param>
			public LandingPageFields(LandingPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// LandingPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.LandingPageID;
				}
				set
				{
					mInstance.LandingPageID = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="LandingPage" /> class.
		/// </summary>
		public LandingPage() : base(CLASS_NAME)
		{
			mFields = new LandingPageFields(this);
		}

		#endregion
	}
}