//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(OrdersHistory.CLASS_NAME, typeof(OrdersHistory))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type OrdersHistory.
	/// </summary>
	public partial class OrdersHistory : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.OrdersHistory";


		/// <summary>
		/// The instance of the class that provides extended API for working with OrdersHistory fields.
		/// </summary>
		private readonly OrdersHistoryFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// OrdersHistoryID.
		/// </summary>
		[DatabaseIDField]
		public int OrdersHistoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("OrdersHistoryID"), 0);
			}
			set
			{
				SetValue("OrdersHistoryID", value);
			}
		}


		/// <summary>
		/// Page title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with OrdersHistory fields.
		/// </summary>
		[RegisterProperty]
		public OrdersHistoryFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with OrdersHistory fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class OrdersHistoryFields : AbstractHierarchicalObject<OrdersHistoryFields>
		{
			/// <summary>
			/// The content item of type OrdersHistory that is a target of the extended API.
			/// </summary>
			private readonly OrdersHistory mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="OrdersHistoryFields" /> class with the specified content item of type OrdersHistory.
			/// </summary>
			/// <param name="instance">The content item of type OrdersHistory that is a target of the extended API.</param>
			public OrdersHistoryFields(OrdersHistory instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// OrdersHistoryID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.OrdersHistoryID;
				}
				set
				{
					mInstance.OrdersHistoryID = value;
				}
			}


			/// <summary>
			/// Page title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="OrdersHistory" /> class.
		/// </summary>
		public OrdersHistory() : base(CLASS_NAME)
		{
			mFields = new OrdersHistoryFields(this);
		}

		#endregion
	}
}