//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(PageTypeBase.CLASS_NAME, typeof(PageTypeBase))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type PageTypeBase.
	/// </summary>
	public partial class PageTypeBase : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.PageTypeBase";


		/// <summary>
		/// The instance of the class that provides extended API for working with PageTypeBase fields.
		/// </summary>
		private readonly PageTypeBaseFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PageTypeBaseID.
		/// </summary>
		[DatabaseIDField]
		public int PageTypeBaseID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PageTypeBaseID"), 0);
			}
			set
			{
				SetValue("PageTypeBaseID", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PageTypeBase fields.
		/// </summary>
		[RegisterProperty]
		public PageTypeBaseFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PageTypeBase fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PageTypeBaseFields : AbstractHierarchicalObject<PageTypeBaseFields>
		{
			/// <summary>
			/// The content item of type PageTypeBase that is a target of the extended API.
			/// </summary>
			private readonly PageTypeBase mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PageTypeBaseFields" /> class with the specified content item of type PageTypeBase.
			/// </summary>
			/// <param name="instance">The content item of type PageTypeBase that is a target of the extended API.</param>
			public PageTypeBaseFields(PageTypeBase instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PageTypeBaseID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PageTypeBaseID;
				}
				set
				{
					mInstance.PageTypeBaseID = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PageTypeBase" /> class.
		/// </summary>
		public PageTypeBase() : base(CLASS_NAME)
		{
			mFields = new PageTypeBaseFields(this);
		}

		#endregion
	}
}