//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ProductBoards.CLASS_NAME, typeof(ProductBoards))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type ProductBoards.
	/// </summary>
	public partial class ProductBoards : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.ProductBoards";


		/// <summary>
		/// The instance of the class that provides extended API for working with ProductBoards fields.
		/// </summary>
		private readonly ProductBoardsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ProductBoardsID.
		/// </summary>
		[DatabaseIDField]
		public int ProductBoardsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProductBoardsID"), 0);
			}
			set
			{
				SetValue("ProductBoardsID", value);
			}
		}


		/// <summary>
		/// Page title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ProductBoards fields.
		/// </summary>
		[RegisterProperty]
		public ProductBoardsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ProductBoards fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductBoardsFields : AbstractHierarchicalObject<ProductBoardsFields>
		{
			/// <summary>
			/// The content item of type ProductBoards that is a target of the extended API.
			/// </summary>
			private readonly ProductBoards mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductBoardsFields" /> class with the specified content item of type ProductBoards.
			/// </summary>
			/// <param name="instance">The content item of type ProductBoards that is a target of the extended API.</param>
			public ProductBoardsFields(ProductBoards instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ProductBoardsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ProductBoardsID;
				}
				set
				{
					mInstance.ProductBoardsID = value;
				}
			}


			/// <summary>
			/// Page title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ProductBoards" /> class.
		/// </summary>
		public ProductBoards() : base(CLASS_NAME)
		{
			mFields = new ProductBoardsFields(this);
		}

		#endregion
	}
}