//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(AccountPage.CLASS_NAME, typeof(AccountPage))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type AccountPage.
	/// </summary>
	public partial class AccountPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.AccountPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with AccountPage fields.
		/// </summary>
		private readonly AccountPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AccountPageID.
		/// </summary>
		[DatabaseIDField]
		public int AccountPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AccountPageID"), 0);
			}
			set
			{
				SetValue("AccountPageID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with AccountPage fields.
		/// </summary>
		[RegisterProperty]
		public AccountPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with AccountPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AccountPageFields : AbstractHierarchicalObject<AccountPageFields>
		{
			/// <summary>
			/// The content item of type AccountPage that is a target of the extended API.
			/// </summary>
			private readonly AccountPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AccountPageFields" /> class with the specified content item of type AccountPage.
			/// </summary>
			/// <param name="instance">The content item of type AccountPage that is a target of the extended API.</param>
			public AccountPageFields(AccountPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AccountPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AccountPageID;
				}
				set
				{
					mInstance.AccountPageID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="AccountPage" /> class.
		/// </summary>
		public AccountPage() : base(CLASS_NAME)
		{
			mFields = new AccountPageFields(this);
		}

		#endregion
	}
}