//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(MenuRoot.CLASS_NAME, typeof(MenuRoot))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type MenuRoot.
	/// </summary>
	public partial class MenuRoot : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.MenuRoot";


		/// <summary>
		/// The instance of the class that provides extended API for working with MenuRoot fields.
		/// </summary>
		private readonly MenuRootFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MenuRootID.
		/// </summary>
		[DatabaseIDField]
		public int MenuRootID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MenuRootID"), 0);
			}
			set
			{
				SetValue("MenuRootID", value);
			}
		}


		/// <summary>
		/// Menu Name.
		/// </summary>
		[DatabaseField]
		public string MenuName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MenuName"), @"Menu");
			}
			set
			{
				SetValue("MenuName", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MenuRoot fields.
		/// </summary>
		[RegisterProperty]
		public MenuRootFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MenuRoot fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MenuRootFields : AbstractHierarchicalObject<MenuRootFields>
		{
			/// <summary>
			/// The content item of type MenuRoot that is a target of the extended API.
			/// </summary>
			private readonly MenuRoot mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MenuRootFields" /> class with the specified content item of type MenuRoot.
			/// </summary>
			/// <param name="instance">The content item of type MenuRoot that is a target of the extended API.</param>
			public MenuRootFields(MenuRoot instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MenuRootID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MenuRootID;
				}
				set
				{
					mInstance.MenuRootID = value;
				}
			}


			/// <summary>
			/// Menu Name.
			/// </summary>
			public string MenuName
			{
				get
				{
					return mInstance.MenuName;
				}
				set
				{
					mInstance.MenuName = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MenuRoot" /> class.
		/// </summary>
		public MenuRoot() : base(CLASS_NAME)
		{
			mFields = new MenuRootFields(this);
		}

		#endregion
	}
}