//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CarouselSection.CLASS_NAME, typeof(CarouselSection))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type CarouselSection.
	/// </summary>
	public partial class CarouselSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.CarouselSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with CarouselSection fields.
		/// </summary>
		private readonly CarouselSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CarouselSectionID.
		/// </summary>
		[DatabaseIDField]
		public int CarouselSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CarouselSectionID"), 0);
			}
			set
			{
				SetValue("CarouselSectionID", value);
			}
		}


		/// <summary>
		/// Larger Height.
		/// </summary>
		[DatabaseField]
		public bool IsLarge
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsLarge"), false);
			}
			set
			{
				SetValue("IsLarge", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CarouselSection fields.
		/// </summary>
		[RegisterProperty]
		public CarouselSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CarouselSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CarouselSectionFields : AbstractHierarchicalObject<CarouselSectionFields>
		{
			/// <summary>
			/// The content item of type CarouselSection that is a target of the extended API.
			/// </summary>
			private readonly CarouselSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CarouselSectionFields" /> class with the specified content item of type CarouselSection.
			/// </summary>
			/// <param name="instance">The content item of type CarouselSection that is a target of the extended API.</param>
			public CarouselSectionFields(CarouselSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CarouselSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CarouselSectionID;
				}
				set
				{
					mInstance.CarouselSectionID = value;
				}
			}


			/// <summary>
			/// Larger Height.
			/// </summary>
			public bool IsLarge
			{
				get
				{
					return mInstance.IsLarge;
				}
				set
				{
					mInstance.IsLarge = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CarouselSection" /> class.
		/// </summary>
		public CarouselSection() : base(CLASS_NAME)
		{
			mFields = new CarouselSectionFields(this);
		}

		#endregion
	}
}