//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CarouselItem.CLASS_NAME, typeof(CarouselItem))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type CarouselItem.
	/// </summary>
	public partial class CarouselItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.CarouselItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with CarouselItem fields.
		/// </summary>
		private readonly CarouselItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CarouselItemID.
		/// </summary>
		[DatabaseIDField]
		public int CarouselItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CarouselItemID"), 0);
			}
			set
			{
				SetValue("CarouselItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Subtitle.
		/// </summary>
		[DatabaseField]
		public string Subtitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Subtitle"), @"");
			}
			set
			{
				SetValue("Subtitle", value);
			}
		}


		/// <summary>
		/// Image Url 1.
		/// </summary>
		[DatabaseField]
		public string ImageUrl1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageUrl1"), @"");
			}
			set
			{
				SetValue("ImageUrl1", value);
			}
		}


		/// <summary>
		/// Image Url 2.
		/// </summary>
		[DatabaseField]
		public string ImageUrl2
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageUrl2"), @"");
			}
			set
			{
				SetValue("ImageUrl2", value);
			}
		}


		/// <summary>
		/// Button Text.
		/// </summary>
		[DatabaseField]
		public string ButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonText"), @"");
			}
			set
			{
				SetValue("ButtonText", value);
			}
		}


		/// <summary>
		/// Button Url.
		/// </summary>
		[DatabaseField]
		public string ButtonUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonUrl"), @"");
			}
			set
			{
				SetValue("ButtonUrl", value);
			}
		}


		/// <summary>
		/// Photo Credit.
		/// </summary>
		[DatabaseField]
		public string PhotoCredit
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhotoCredit"), @"");
			}
			set
			{
				SetValue("PhotoCredit", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CarouselItem fields.
		/// </summary>
		[RegisterProperty]
		public CarouselItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CarouselItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CarouselItemFields : AbstractHierarchicalObject<CarouselItemFields>
		{
			/// <summary>
			/// The content item of type CarouselItem that is a target of the extended API.
			/// </summary>
			private readonly CarouselItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CarouselItemFields" /> class with the specified content item of type CarouselItem.
			/// </summary>
			/// <param name="instance">The content item of type CarouselItem that is a target of the extended API.</param>
			public CarouselItemFields(CarouselItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CarouselItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CarouselItemID;
				}
				set
				{
					mInstance.CarouselItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Subtitle.
			/// </summary>
			public string Subtitle
			{
				get
				{
					return mInstance.Subtitle;
				}
				set
				{
					mInstance.Subtitle = value;
				}
			}


			/// <summary>
			/// Image Url 1.
			/// </summary>
			public string ImageUrl1
			{
				get
				{
					return mInstance.ImageUrl1;
				}
				set
				{
					mInstance.ImageUrl1 = value;
				}
			}


			/// <summary>
			/// Image Url 2.
			/// </summary>
			public string ImageUrl2
			{
				get
				{
					return mInstance.ImageUrl2;
				}
				set
				{
					mInstance.ImageUrl2 = value;
				}
			}


			/// <summary>
			/// Button Text.
			/// </summary>
			public string ButtonText
			{
				get
				{
					return mInstance.ButtonText;
				}
				set
				{
					mInstance.ButtonText = value;
				}
			}


			/// <summary>
			/// Button Url.
			/// </summary>
			public string ButtonUrl
			{
				get
				{
					return mInstance.ButtonUrl;
				}
				set
				{
					mInstance.ButtonUrl = value;
				}
			}


			/// <summary>
			/// Photo Credit.
			/// </summary>
			public string PhotoCredit
			{
				get
				{
					return mInstance.PhotoCredit;
				}
				set
				{
					mInstance.PhotoCredit = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CarouselItem" /> class.
		/// </summary>
		public CarouselItem() : base(CLASS_NAME)
		{
			mFields = new CarouselItemFields(this);
		}

		#endregion
	}
}