//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CartPage.CLASS_NAME, typeof(CartPage))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type CartPage.
	/// </summary>
	public partial class CartPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.CartPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with CartPage fields.
		/// </summary>
		private readonly CartPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CartPageID.
		/// </summary>
		[DatabaseIDField]
		public int CartPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CartPageID"), 0);
			}
			set
			{
				SetValue("CartPageID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), @"");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CartPage fields.
		/// </summary>
		[RegisterProperty]
		public CartPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CartPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CartPageFields : AbstractHierarchicalObject<CartPageFields>
		{
			/// <summary>
			/// The content item of type CartPage that is a target of the extended API.
			/// </summary>
			private readonly CartPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CartPageFields" /> class with the specified content item of type CartPage.
			/// </summary>
			/// <param name="instance">The content item of type CartPage that is a target of the extended API.</param>
			public CartPageFields(CartPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CartPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CartPageID;
				}
				set
				{
					mInstance.CartPageID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CartPage" /> class.
		/// </summary>
		public CartPage() : base(CLASS_NAME)
		{
			mFields = new CartPageFields(this);
		}

		#endregion
	}
}