//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactPageMenu.CLASS_NAME, typeof(ContactPageMenu))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type ContactPageMenu.
	/// </summary>
	public partial class ContactPageMenu : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.ContactPageMenu";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactPageMenu fields.
		/// </summary>
		private readonly ContactPageMenuFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DropDownListID.
		/// </summary>
		[DatabaseIDField]
		public int DropDownListID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DropDownListID"), 0);
			}
			set
			{
				SetValue("DropDownListID", value);
			}
		}


		/// <summary>
		/// Menu type.
		/// </summary>
		[DatabaseField]
		public string menuType
		{
			get
			{
				return ValidationHelper.GetString(GetValue("menuType"), @"");
			}
			set
			{
				SetValue("menuType", value);
			}
		}


		/// <summary>
		/// Drop-down list title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactPageMenu fields.
		/// </summary>
		[RegisterProperty]
		public ContactPageMenuFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactPageMenu fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactPageMenuFields : AbstractHierarchicalObject<ContactPageMenuFields>
		{
			/// <summary>
			/// The content item of type ContactPageMenu that is a target of the extended API.
			/// </summary>
			private readonly ContactPageMenu mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactPageMenuFields" /> class with the specified content item of type ContactPageMenu.
			/// </summary>
			/// <param name="instance">The content item of type ContactPageMenu that is a target of the extended API.</param>
			public ContactPageMenuFields(ContactPageMenu instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DropDownListID.
			/// </summary>
			public int DropDownListID
			{
				get
				{
					return mInstance.DropDownListID;
				}
				set
				{
					mInstance.DropDownListID = value;
				}
			}


			/// <summary>
			/// Menu type.
			/// </summary>
			public string menuType
			{
				get
				{
					return mInstance.menuType;
				}
				set
				{
					mInstance.menuType = value;
				}
			}


			/// <summary>
			/// Drop-down list title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactPageMenu" /> class.
		/// </summary>
		public ContactPageMenu() : base(CLASS_NAME)
		{
			mFields = new ContactPageMenuFields(this);
		}

		#endregion
	}
}