//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactPage.CLASS_NAME, typeof(ContactPage))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type ContactPage.
	/// </summary>
	public partial class ContactPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.ContactPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactPage fields.
		/// </summary>
		private readonly ContactPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactPageID.
		/// </summary>
		[DatabaseIDField]
		public int ContactPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactPageID"), 0);
			}
			set
			{
				SetValue("ContactPageID", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactPage fields.
		/// </summary>
		[RegisterProperty]
		public ContactPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactPageFields : AbstractHierarchicalObject<ContactPageFields>
		{
			/// <summary>
			/// The content item of type ContactPage that is a target of the extended API.
			/// </summary>
			private readonly ContactPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactPageFields" /> class with the specified content item of type ContactPage.
			/// </summary>
			/// <param name="instance">The content item of type ContactPage that is a target of the extended API.</param>
			public ContactPageFields(ContactPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactPageID;
				}
				set
				{
					mInstance.ContactPageID = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactPage" /> class.
		/// </summary>
		public ContactPage() : base(CLASS_NAME)
		{
			mFields = new ContactPageFields(this);
		}

		#endregion
	}
}