//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ContactPageMenuItem.CLASS_NAME, typeof(ContactPageMenuItem))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type ContactPageMenuItem.
	/// </summary>
	public partial class ContactPageMenuItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.ContactPageMenuItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactPageMenuItem fields.
		/// </summary>
		private readonly ContactPageMenuItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DropDownListItemID.
		/// </summary>
		[DatabaseIDField]
		public int DropDownListItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DropDownListItemID"), 0);
			}
			set
			{
				SetValue("DropDownListItemID", value);
			}
		}


		/// <summary>
		/// Drop-down list item name.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactPageMenuItem fields.
		/// </summary>
		[RegisterProperty]
		public ContactPageMenuItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactPageMenuItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactPageMenuItemFields : AbstractHierarchicalObject<ContactPageMenuItemFields>
		{
			/// <summary>
			/// The content item of type ContactPageMenuItem that is a target of the extended API.
			/// </summary>
			private readonly ContactPageMenuItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactPageMenuItemFields" /> class with the specified content item of type ContactPageMenuItem.
			/// </summary>
			/// <param name="instance">The content item of type ContactPageMenuItem that is a target of the extended API.</param>
			public ContactPageMenuItemFields(ContactPageMenuItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DropDownListItemID.
			/// </summary>
			public int DropDownListItemID
			{
				get
				{
					return mInstance.DropDownListItemID;
				}
				set
				{
					mInstance.DropDownListItemID = value;
				}
			}


			/// <summary>
			/// Drop-down list item name.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactPageMenuItem" /> class.
		/// </summary>
		public ContactPageMenuItem() : base(CLASS_NAME)
		{
			mFields = new ContactPageMenuItemFields(this);
		}

		#endregion
	}
}