//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.ShawContract;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(HomePage.CLASS_NAME, typeof(HomePage))]

namespace CMS.DocumentEngine.Types.ShawContract
{
	/// <summary>
	/// Represents a content item of type HomePage.
	/// </summary>
	public partial class HomePage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "ShawContract.HomePage";


		/// <summary>
		/// The instance of the class that provides extended API for working with HomePage fields.
		/// </summary>
		private readonly HomePageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HomePageID.
		/// </summary>
		[DatabaseIDField]
		public int HomePageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HomePageID"), 0);
			}
			set
			{
				SetValue("HomePageID", value);
			}
		}


		/// <summary>
		/// Custom CSS Class.
		/// </summary>
		[DatabaseField]
		public string CustomCSSClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CustomCSSClass"), @"");
			}
			set
			{
				SetValue("CustomCSSClass", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with HomePage fields.
		/// </summary>
		[RegisterProperty]
		public HomePageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HomePage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomePageFields : AbstractHierarchicalObject<HomePageFields>
		{
			/// <summary>
			/// The content item of type HomePage that is a target of the extended API.
			/// </summary>
			private readonly HomePage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomePageFields" /> class with the specified content item of type HomePage.
			/// </summary>
			/// <param name="instance">The content item of type HomePage that is a target of the extended API.</param>
			public HomePageFields(HomePage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HomePageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HomePageID;
				}
				set
				{
					mInstance.HomePageID = value;
				}
			}


			/// <summary>
			/// Custom CSS Class.
			/// </summary>
			public string CustomCSSClass
			{
				get
				{
					return mInstance.CustomCSSClass;
				}
				set
				{
					mInstance.CustomCSSClass = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HomePage" /> class.
		/// </summary>
		public HomePage() : base(CLASS_NAME)
		{
			mFields = new HomePageFields(this);
		}

		#endregion
	}
}