// <auto-generated />
namespace ShawContract.Providers.ProductBoard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updateproductboardmodeladdviewlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateproductboardmodeladdviewlog));
        
        string IMigrationMetadata.Id
        {
            get { return "202001231506220_update-product-board-model-add-view-log"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
